services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=akinita
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U dbuser -d akinita
      interval: 30s
      timeout: 60s
      retries: 3
    volumes:
      - 'akinitadb:/var/lib/postgresql/data/'
  spring:
    image: sp
    build:
      context: ./Akinita
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/akinita
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=pass123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 60s
      retries: 3

  email:
    image: email
    build:
      context: ./EmailService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 60s
      retries: 3
volumes:
  akinitadb: