appdir: "{{ ansible_user_dir }}/spring"
branch: "main"
appuser: "{{ansible_user_id}}"
appgroup: "{{ansible_user_gid}}"
app_port: 8080

app:
  env:
    server.port: "{{app_port}}"
    spring.datasource.username: appuser
    spring.datasource.password: apppassword
    spring.datasource.url: jdbc:postgresql://localhost:5432/appdb

service:
  workingdir: "{{ ansible_user_dir }}/spring"
  execstart: "java -jar {{ ansible_user_dir }}/spring//Akinita/Akinita/target/ds-lab-2024-0.0.1-SNAPSHOT.jar"
  execstart2: "java -jar {{ ansible_user_dir }}/spring/EmailService/target/EmailService-0.0.1-SNAPSHOT.jar"
  docker_compose_file: "{{ appdir }}/docker-compose.yaml"
