---
- hosts: localhost
  gather_facts: no
  collections:
    - kubernetes.core

  vars:
    kubeconfig: "{{ lookup('env','KUBECONFIG') }}"  
    workspace: "{{ lookup('env','WORKSPACE') | default('/var/lib/jenkins/workspace/K8S') }}"

  tasks:
    - name: Apply Spring Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        src: "{{ workspace }}/k8s/Akinita-spring/spring-deployment.yaml"
        state: present

    - name: Apply Spring Service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        src: "{{ workspace }}/k8s/Akinita-spring/spring-service.yaml"
        state: present

    - name: Apply Spring Ingress
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        src: "{{ workspace }}/k8s/Akinita-spring/spring-ingress.yaml"
        state: present

    - name: Apply Postgres Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        src: "{{ workspace }}/k8s/postgres/postgres-deployment.yaml"
        state: present

    - name: Apply Postgres Persistent Volume
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        src: "{{ workspace }}/k8s/postgres/postgres-pvc.yaml"
        state: present

    - name: Apply Postgres Service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        src: "{{ workspace }}/k8s/postgres/postgres-svc.yaml"
        state: present

    - name: Apply Email Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        src: "{{ workspace }}/k8s/Email/email-deployment.yaml"
        state: present

    - name: Apply Email Service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        src: "{{ workspace }}/k8s/Email/email-service.yaml"
        state: present
