- hosts: localhost
  gather_facts: no
  collections:
    - kubernetes.core
  tasks:
    - name: Apply Spring Deployment
      kubernetes.core.k8s:
        src: ../k8s/Akinita-Spring/spring-deployment.yaml
        state: present

    - name: Apply Spring Service
      kubernetes.core.k8s:
        src: ../k8s/Akinita-Spring/spring-service.yaml
        state: present

    - name: Apply Spring Ingress
      kubernetes.core.k8s:
        src: ../k8s/Akinita-Spring/spring-ingress.yaml
        state: present

    - name: Apply Postgres Deployment
      kubernetes.core.k8s:
        src: ../k8s/Postgres/postgres-deployment.yaml
        state: present

    - name: Apply Postgres Persistent Volume
      kubernetes.core.k8s:
      src: ../k8s/Postgres/postgres-pvc.yaml
      state: present

    - name: Apply Postgres Service
      kubernetes.core.k8s:
        src: ../k8s/Postgres/postgres-svc.yaml
        state: present

    - name: Apply Email Deployment
      kubernetes.core.k8s:
        src: ../kapou mesa sto project/Postgres/email-deployment.yaml
        state: present


