---
- name: Install and configure PostgreSQL
  hosts: dbservers
  become: yes
  become_user: root
  vars:
    db:
      user: myuser
      password: mypassword
      name: mydb

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: 
          - postgresql
          - python3-pip
          - python3-psycopg2
        state: present
        update_cache: yes
      tags: [install]

    - block:
        - name: Edit postgresql.conf to allow all addresses
          lineinfile:
            path: /etc/postgresql/16/main/postgresql.conf
            regexp: '^#listen_addresses ='
            line: "listen_addresses = '*'"
          notify: restart postgres
          tags: [edit]

        - name: Allow MD5 auth for all IPs
          lineinfile:
            path: /etc/postgresql/16/main/pg_hba.conf
            line: "host    all             all             0.0.0.0/0               md5"
            create: yes
          notify: restart postgres
          tags: [edit]
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'

    - name: Ensure Postgres user exists
      postgresql_user:
        name: "{{ db.user }}"
        password: "{{ db.password }}"
      become: yes
      tags: [db]

    - name: Ensure Postgres database exists
      postgresql_db:
        name: "{{ db.name }}"
        owner: "{{ db.user }}"
      become: yes
      tags: [db]


  handlers:
    - name: restart postgres
      service:
        name: postgresql
        state: restarted