- name: Install MicroK8s and enable essential add-ons on remote VM
  hosts: k8s-vm

  tasks:
  - name: Check if snap is installed
    shell: snap version
    register: snap_installed_result_remote
    ignore_errors: true
  
  - name: Check if microk8s is installed
    shell: snap info microk8s 
    register: microk8s_installed_result_remote
    ignore_errors: true

  - name: Set snap and microk8s Fact
    set_fact:
      snap_installed_remote: "{{ snap_installed_result_remote.rc == 0 }}"
      microk8s_installed_remote: "{{ microk8s_installed_result_remote.rc == 0 }}"

- hosts: localhost
  gather_facts: no

  vars:
    kubeconfig: "{{ lookup('env','KUBECONFIG') }}"
    workspace: "{{ lookup('env','WORKSPACE') | default('/var/lib/jenkins/workspace/K8S') }}"
    microk8s_ip: "{{ microk8s_ip }}"
    jenkins_ip: "{{ jenkins_ip }}"
    jenkins_user: "{{ jenkins_user }}"
    jenkins_token: "{{ jenkins_token }}"

  tasks:
  - name: Install-microk8s playbook if snap or microk8s not installed
    include_tasks: install-microk8s.yaml
    vars:
      microk8s_ip: "{{ microk8s_ip }}"
      jenkins_ip: "{{ jenkins_ip }}"
      jenkins_user: "{{ jenkins_user }}"
      jenkins_token: "{{ jenkins_token }}"
    when: not hostvars['k8s_vm'].snap_installed_result_remote or not hostvars['k8s_vm'].microk8s_installed_result_remote