apiVersion: apps/v1
kind: Deployment
metadata:
  name:  email-deployment
  namespace: default
  labels:
    app: email
spec:
  selector:
    matchLabels:
      app: email
  replicas: 1
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name:  email
        image: ghcr.io/zachariasliodakis/devops/emailservice:latest
        livenessProbe:
          httpGet:
            path: "/actuator/health/liveness"
            port: 8081
          failureThreshold: 20
          periodSeconds: 10
          initialDelaySeconds: 30
        readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8081
            failureThreshold: 10
            periodSeconds: 10
            initialDelaySeconds: 30
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/dsdb
        - name: SPRING_DATASOURCE_USERNAME
          value: dbuser
        - name: SPRING_DATASOURCE_PASSWORD
          value: pass123
        ports:
        - containerPort:  8081
          name:  spring
      imagePullSecrets:
      - name: registry-credentials