apiVersion: v1
kind: Service
metadata:
  labels:
    app: email
  name: email
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      name: email
  selector:
    app: email
  type: ClusterIP