---
control:
  hosts:
    local-control:
      ansible_connection: local
    control-vm:
      ansible_host: control

azure-hosts:
  hosts:
    devops-vm:
      ansible_host: "{{ vm_ip }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'